"""Load CSV files into PostgreSQL database.

This script loads CSV files (generated by upload_data.py) into a PostgreSQL database.
"""

import argparse
import asyncio
import pathlib
import dotenv

from csv_to_db_loader import CSVToDBLoader, AsyncCSVToDBLoader

dotenv.load_dotenv(".env")


def load_csvs_to_database(
    csv_dir: pathlib.Path, conn_string: str, clear_tables: bool = False
):
    """Load CSV files into database synchronously.

    Args:
        csv_dir: Directory containing CSV files
        conn_string: PostgreSQL connection string
        clear_tables: If True, truncate tables before loading
    """
    print(f"Loading CSV files from {csv_dir} into database\n")

    try:
        loader = CSVToDBLoader(conn_string=conn_string)
    except ConnectionError as e:
        print(f"{e}")
        return 1
    except Exception as e:
        print(f"\n❌ Unexpected error during connection:\n{e}")
        return 1

    try:
        results = loader.load_csv_directory(
            str(csv_dir),
            commit=True,
            clear_tables=clear_tables,
            progress_callback=lambda table, count: print(
                f"  → {table}: {count:,} rows"
            ),
        )

        print("\n" + "=" * 60)
        print("✅ SUCCESS - All data loaded!")
        print("=" * 60)
        total_rows = 0
        for table, count in results.items():
            print(f"  {table:30s} {count:>10,} rows")
            total_rows += count
        print("=" * 60)
        print(f"  {'TOTAL':30s} {total_rows:>10,} rows")
        print("=" * 60)
        return 0

    except Exception as e:
        print(f"\n❌ Error during data load:\n{e}")
        return 1
    finally:
        loader.close()


async def load_csvs_to_database_async(
    csv_dir: pathlib.Path, conn_string: str, clear_tables: bool = False
):
    """Load CSV files into database asynchronously.

    Args:
        csv_dir: Directory containing CSV files
        conn_string: PostgreSQL connection string
        clear_tables: If True, truncate tables before loading
    """
    print(f"Loading CSV files from {csv_dir} into database (async)\n")

    try:
        async_loader = AsyncCSVToDBLoader(conn_string=conn_string, max_workers=1)
    except ConnectionError as e:
        print(f"{e}")
        return 1
    except Exception as e:
        print(f"\n❌ Unexpected error during connection:\n{e}")
        return 1

    try:
        results = await async_loader.load_csv_directory_async(
            str(csv_dir),
            commit=True,
            clear_tables=clear_tables,
            progress_callback=lambda table, count: print(
                f"  → {table}: {count:,} rows"
            ),
        )

        print("\n" + "=" * 60)
        print("✅ SUCCESS - All data loaded!")
        print("=" * 60)
        total_rows = 0
        for table, count in results.items():
            print(f"  {table:30s} {count:>10,} rows")
            total_rows += count
        print("=" * 60)
        print(f"  {'TOTAL':30s} {total_rows:>10,} rows")
        print("=" * 60)
        return 0

    except Exception as e:
        print(f"\n❌ Error during data load:\n{e}")
        return 1
    finally:
        await async_loader.close()


def main():
    parser = argparse.ArgumentParser(
        description="Load CSV files into PostgreSQL database"
    )
    parser.add_argument(
        "--csv-dir",
        type=pathlib.Path,
        default=pathlib.Path("./csv_output"),
        help="Directory containing CSV files (default: ./csv_output)",
    )
    parser.add_argument(
        "--async",
        dest="use_async",
        action="store_true",
        help="Use async loading (default: synchronous)",
    )
    parser.add_argument(
        "--clear-tables",
        action="store_true",
        help="Clear all tables before loading (removes all existing data)",
    )

    args = parser.parse_args()

    # Validate CSV directory exists
    if not args.csv_dir.exists():
        print(f"Error: CSV directory {args.csv_dir} does not exist")
        return

    # Get connection string from environment
    conn_string = dotenv.get_key(".env", "CONN_STRING")
    if not conn_string:
        print("Error: CONN_STRING not found in .env file")
        return

    # Load CSVs
    try:
        if args.use_async:
            exit_code = asyncio.run(
                load_csvs_to_database_async(
                    args.csv_dir, conn_string, args.clear_tables
                )
            )
        else:
            exit_code = load_csvs_to_database(
                args.csv_dir, conn_string, args.clear_tables
            )

        exit(exit_code if exit_code is not None else 0)
    except KeyboardInterrupt:
        print("\n\n⚠️  Operation cancelled by user")
        exit(130)


if __name__ == "__main__":
    main()
